### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by sebgoa** [resmo/ansible-cloudstack#1]
Great work, thanks a lot for this.

Where do I put this if I have my own ansible installation (meaning I install ansible from source) ?

thanks

**Comment by resmo** [comment]
create a `ansible.cfg` file in your projects root and create a directory `library` where you put all the custom modules in it (you can even have directories in it, so `git submodule` is your friend)

```
$ cd project
$ mkdir library
$ git submodule add git@github.com:resmo/ansible-cloudstack.git library/cloudstack
$ git submodule update --init
$ cat ansible.cfg
[defaults]
library = /usr/share/ansible:library
```

**Comment by sebgoa** [comment]
got it, thanks
