### ISSUE TITLE
URL encode doesn't work?!

### ISSUE THREAD

**Issue by xied75** [resmo/ansible-cloudstack#11]
Did you ever try register ISO with a URL?

I got an error like this:

```
TASK: [test] ****************************************************************** 
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: CloudStackException: ('HTTP 431 response from CloudStack', <Response [431]>, {u'errorcode': 431, u'uuidList': [], u'cserrorcode': 9999, u'errortext': u'Unsupported scheme for url: http%3A%2F%2Fstable.release.core-os.net%2Famd64-usr%2Fcurrent%2Fcoreos_production_iso_image.iso'})
```

I did try cloudmonkey and it works. Seems the endpoint doesn't like this kind of encoding?

Best,

Dong

**Comment by resmo** [comment]
yes, I did. can you print the URL you used in here?

**Comment by xied75** [comment]
Hi, Thanks for reply so quick. :)

The url is simply: http://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso

If on your side it does work, do you mind to share your yaml here?

Best regards,

Dong

**Comment by xied75** [comment]
This can be closed now. I just found out that the endpoint I'm calling is not handling 'post' properly, yet 'get' can pass through ok. That's why cloudmonkey is working because its default action is 'get'.

**Comment by resmo** [comment]
good to hear, was curious about that problem.
