### ISSUE TITLE
sshkeypair not checking finger print

### ISSUE THREAD

**Issue by xied75** [resmo/ansible-cloudstack#20]
It only check the name currently. Given we know the public key during runtime, we should be able to generate the finger print and use that in the query other than the name. Not sure how easy was it to do it in Python though.

Best,

Dong

**Comment by resmo** [comment]
if you use `public_key` param, the fingerprint is foing to be checked.

**Comment by resmo** [comment]
@xied75 or could you give me some more infos?

**Comment by xied75** [comment]
In the file

```
 def get_ssh_key(self):
        if not self.ssh_key:
            args = {}
            args['projectid'] = self.get_project_id()
            args['name'] = self.module.params.get('name')

            ssh_keys = self.cs.listSSHKeyPairs(**args)
            if ssh_keys and 'sshkeypair' in ssh_keys:
                self.ssh_key = ssh_keys['sshkeypair'][0]
        return self.ssh_key
```

If I already have key A with fingerprint aaa, in my playbook I tried to add key named A again yet with fingerprint bbb, ansible should detect this is in fact a new key therefore remove the old and upload the new, but the above code is not checking fingerprint. Thus I thought I'm using my bbb key yet I can't login to my machine with aaa in .ssh/ of the vm. :)

**Comment by resmo** [comment]
Still can not confirm your experiences: Look at https://github.com/resmo/ansible-cloudstack/blob/master/cs_sshkeypair.py#L334 and also see the test playbook
