### ISSUE TITLE
are we going to handle egress rule as in listEgressFirewallRules etc.

### ISSUE THREAD

**Issue by xied75** [resmo/ansible-cloudstack#22]
In the API those:

createEgressFirewallRule (A)
deleteEgressFirewallRule (A)
listEgressFirewallRules
updateEgressFirewallRule (A)

were listed under Firewall, so not sure should this be a separate module or part of the firewall one you already done.

Best,

Dong

**Comment by resmo** [comment]
Hi @xied75 

Would be super easy to implement in the current `cs_firewall`. I already did some similar work in `cs_securitygroup_rule`. I am working on it.

**Comment by resmo** [comment]
cs_firewall in ansible 2.0 will have egress support: https://github.com/ansible/ansible-modules-extras/pull/510

**Comment by resmo** [comment]
updated!
