### ISSUE TITLE
Time out with maximum retries reached

### ISSUE THREAD

**Issue by sebgoa** [resmo/ansible-cloudstack#43]
On a cloudstack cloud with an advanced zone we see lots of HTTPS errors due to maximum connection retries reached.

While it might be a setup/limit issue on the cloud. Is there a way to configure Ansible to avoid those issues, increase the time during polls on the API ?

This error is seen with a simple play that starts a single instance. the instance actually starts but the play fails. So ansible has to be doing multiple cs polls. to get the status of the VM (async, job status poll).

**Comment by resmo** [comment]
@runseb not sure if it helps but you can increase the timeout e.g. by a setting in cloudstack.ini

``` ini
[cloudstack]
...
timeout = 30
```

**Comment by sebgoa** [comment]
so the answer turned out to be use

[cloudstack]
...
poll = 30

Which makes Ansible poll for the status of async calls only every _poll_ seconds...

So I will close the issue. thanks
