### ISSUE TITLE
Add tag support

### ISSUE THREAD

**Issue by sebgoa** [resmo/ansible-cloudstack#9]
@resmo me again, trolling…:)

Would love to see tag support. So we can tag VMs.

**Comment by resmo** [comment]
sure! Will have some time soon :wink:

**Comment by resmo** [comment]
hi @runseb I didn't find a way using the api to _tag_ a VM. How is this supposed to work in terms of what API command do I have to use? enlighten me please :)

**Comment by sebgoa** [comment]
easiest is probably to look at libcloud: https://github.com/apache/libcloud/blob/trunk/libcloud/compute/drivers/cloudstack.py#L3503
@resmo

**Comment by resmo** [comment]
I created my own dynamic inventory for cloudstack only, see https://github.com/resmo/ansible-cloudstack/blob/master/cloudstack.py . There is a PR hanging for it to be merged https://github.com/ansible/ansible/pull/9835
